AllCops:
  NewCops: enable
Naming/MethodParameterName:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/LambdaCall:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Style/RedundantFileExtensionInRequire:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Metrics/MethodLength:
  Max: 29
Metrics/AbcSize:
  Max: 43
